/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package testeinterface;

import java.util.ArrayList;

/**
 *
 * @author uilian
 */
public class CadastroClientes extends javax.swing.JInternalFrame {
    String nome,telefone,datanasc, rua,cpf,numero,bairro,cep;

    /**
     * Creates new form CadastroClientes
     */
    public CadastroClientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtnome = new javax.swing.JTextField();
        jtrua = new javax.swing.JTextField();
        jttelefone = new javax.swing.JTextField();
        jbnovo = new javax.swing.JButton();
        jbsalvar = new javax.swing.JButton();
        jblimpar = new javax.swing.JButton();
        jbfechar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtdatanasc = new javax.swing.JTextField();
        jtrg = new javax.swing.JTextField();
        jtnumero = new javax.swing.JTextField();
        jtbairro = new javax.swing.JTextField();
        jtcep = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jtcpf = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 0, 204));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Cadastro Clientes");
        getContentPane().setLayout(null);

        jtnome.setEnabled(false);
        getContentPane().add(jtnome);
        jtnome.setBounds(80, 180, 236, 28);

        jtrua.setEnabled(false);
        jtrua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtruaActionPerformed(evt);
            }
        });
        getContentPane().add(jtrua);
        jtrua.setBounds(120, 250, 114, 26);

        jttelefone.setEnabled(false);
        getContentPane().add(jttelefone);
        jttelefone.setBounds(330, 260, 114, 25);

        jbnovo.setText("novo");
        jbnovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnovoActionPerformed(evt);
            }
        });
        getContentPane().add(jbnovo);
        jbnovo.setBounds(760, 10, 100, 41);

        jbsalvar.setText("salvar");
        jbsalvar.setEnabled(false);
        jbsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbsalvarActionPerformed(evt);
            }
        });
        getContentPane().add(jbsalvar);
        jbsalvar.setBounds(760, 60, 95, 41);

        jblimpar.setText("limpar");
        jblimpar.setEnabled(false);
        jblimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jblimparActionPerformed(evt);
            }
        });
        getContentPane().add(jblimpar);
        jblimpar.setBounds(770, 120, 100, 41);

        jbfechar.setText("fechar");
        jbfechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbfecharActionPerformed(evt);
            }
        });
        getContentPane().add(jbfechar);
        jbfechar.setBounds(780, 180, 100, 41);

        jLabel1.setText("nome:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 180, 60, 28);

        jLabel2.setText("endereco:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(180, 270, 49, 26);

        jLabel3.setText("Telefone:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(240, 270, 46, 25);

        jLabel4.setText("Data nasc:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(330, 180, 65, 28);

        jLabel5.setText("RG:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(470, 184, 40, 20);

        jtdatanasc.setEnabled(false);
        jtdatanasc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtdatanascActionPerformed(evt);
            }
        });
        getContentPane().add(jtdatanasc);
        jtdatanasc.setBounds(390, 180, 64, 28);

        jtrg.setEnabled(false);
        jtrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtrgActionPerformed(evt);
            }
        });
        getContentPane().add(jtrg);
        jtrg.setBounds(500, 190, 81, 20);

        jtnumero.setEnabled(false);
        getContentPane().add(jtnumero);
        jtnumero.setBounds(530, 240, 42, 20);

        jtbairro.setEnabled(false);
        jtbairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbairroActionPerformed(evt);
            }
        });
        getContentPane().add(jtbairro);
        jtbairro.setBounds(393, 67, 153, 26);

        jtcep.setEnabled(false);
        getContentPane().add(jtcep);
        jtcep.setBounds(591, 70, 76, 23);

        jLabel6.setText("Logradouro: ");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(50, 250, 62, 26);

        jLabel7.setText("N°:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(480, 240, 16, 26);

        jLabel8.setText("Bairro:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(357, 67, 32, 26);

        jLabel9.setText("CEP:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(564, 67, 23, 26);

        jLabel10.setText("UF:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(540, 140, 17, 26);

        jLabel11.setText("CPF:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(600, 190, 40, 14);

        jtcpf.setEnabled(false);
        jtcpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtcpfActionPerformed(evt);
            }
        });
        getContentPane().add(jtcpf);
        jtcpf.setBounds(640, 190, 84, 20);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Alagoas ", "Amapá ", "Amazonas ", "Bahia ", "Ceará ", "Distrito Federal ", "Espírito Santo ", "Goiás ", "Maranhão", "Mato Grosso ", "Mato Grosso do Sul ", "Minas Gerais ", "Pará ", "Paraíba ", "Paraná ", "Pernambuco ", "Piauí ", "Roraima ", "Rondônia ", "Rio de Janeiro ", "Rio Grande do Norte ", "Rio Grande do Sul", "Santa Catarina ", "São Paulo ", "Sergipe ", "Tocantins  ", " " }));
        jComboBox1.setEnabled(false);
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(590, 140, 126, 23);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testeinterface/walmart.jpg"))); // NOI18N
        jLabel12.setText("jLabel12");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(20, 10, 260, 130);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtruaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtruaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtruaActionPerformed

    private void jbsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbsalvarActionPerformed
       
     nome=jtnome.getText();
     rua =jtrua.getText();
     telefone=jttelefone.getText();
     datanasc =jtdatanasc.getText();
     String rg=jtrg.getText();
    String uf=(String) jComboBox1.getSelectedItem();
    cpf=jtcpf.getText();
    numero= jtnumero.getText();
    bairro=jtbairro.getText();
    cep=jtcep.getText();
    rg=jtrg.getText();
    ArrayList lista= new ArrayList();
    
    
    
    
    
    

     
    
     System.out.println("Nome: " + nome + "\nData nascimento:" + datanasc +"\n RG: "+ rg + "\nCPF:"+ cpf +"\nRua: " + rua +"\nNumero:"+numero+"\nBairro"+bairro+"\nCEP"+cep+ "\nEstado: " +uf+"\n"+"telefone:"+telefone );
    }//GEN-LAST:event_jbsalvarActionPerformed

    private void jbfecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbfecharActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jbfecharActionPerformed

    private void jbnovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnovoActionPerformed
        // TODO add your handling code here:
       
        jtnome.setEnabled(true);
        jtrua.setEnabled(true);
        jttelefone.setEnabled(true);
        jbsalvar.setEnabled(true);
        jblimpar.setEnabled(true);
        jtdatanasc.setEnabled(true);
        jtrg.setEnabled(true);
        jtcpf.setEnabled(true);
        jComboBox1.setEnabled(true);
        jtcep.setEnabled(true);
        jtbairro.setEnabled(true);
        jtnumero.setEnabled(true);
        
        
        //jtemail.setEnabled(true);
        
    }//GEN-LAST:event_jbnovoActionPerformed

    private void jblimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jblimparActionPerformed

        // TODO add your handling code here:
        jtnome.setText(null);
        jtrua.setText(null);
        jttelefone.setText(null);
        jtdatanasc.setText(null);
        jtrg.setText(null);
        jtcpf.setText(null);
        jtcep.setText(null);
        jtbairro.setText(null);
        jtnumero.setText(null);
        
        
    }//GEN-LAST:event_jblimparActionPerformed

    private void jtdatanascActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtdatanascActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtdatanascActionPerformed

    private void jtbairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtbairroActionPerformed

    private void jtcpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtcpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtcpfActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jtrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtrgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtrgActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton jbfechar;
    private javax.swing.JButton jblimpar;
    private javax.swing.JButton jbnovo;
    private javax.swing.JButton jbsalvar;
    private javax.swing.JTextField jtbairro;
    private javax.swing.JTextField jtcep;
    private javax.swing.JTextField jtcpf;
    private javax.swing.JTextField jtdatanasc;
    private javax.swing.JTextField jtnome;
    private javax.swing.JTextField jtnumero;
    private javax.swing.JTextField jtrg;
    private javax.swing.JTextField jtrua;
    private javax.swing.JTextField jttelefone;
    // End of variables declaration//GEN-END:variables
}


