/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package testeinterface;

import javax.swing.JOptionPane;

/**
 *
 * @author uilian
 */
public class Painel extends javax.swing.JFrame {
    
    String nome,endereco,telefone,email;

    /**
     * Creates new form Painel
     */
    public Painel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtnome = new javax.swing.JTextField();
        jbnovo = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jbenviar = new javax.swing.JButton();
        jblimpar = new javax.swing.JButton();
        jbfechar = new javax.swing.JButton();
        jtendereco = new javax.swing.JTextField();
        jttelefone = new javax.swing.JTextField();
        jtemail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de Clientes");
        setMinimumSize(new java.awt.Dimension(240, 240));
        getContentPane().setLayout(null);

        jLabel1.setText("nome:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(25, 11, 83, 28);

        jtnome.setEnabled(false);
        jtnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtnomeActionPerformed(evt);
            }
        });
        getContentPane().add(jtnome);
        jtnome.setBounds(30, 40, 260, 40);

        jbnovo.setText("novo");
        jbnovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnovoActionPerformed(evt);
            }
        });
        getContentPane().add(jbnovo);
        jbnovo.setBounds(40, 316, 129, 41);

        jLabel2.setText("endereço:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 80, 114, 27);

        jLabel3.setText("Telefone:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 150, 112, 21);

        jbenviar.setText("enviar");
        jbenviar.setEnabled(false);
        jbenviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbenviarActionPerformed(evt);
            }
        });
        getContentPane().add(jbenviar);
        jbenviar.setBounds(217, 316, 169, 41);

        jblimpar.setText("limpar");
        jblimpar.setEnabled(false);
        jblimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jblimparActionPerformed(evt);
            }
        });
        getContentPane().add(jblimpar);
        jblimpar.setBounds(40, 361, 129, 42);

        jbfechar.setText("fechar");
        jbfechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbfecharActionPerformed(evt);
            }
        });
        getContentPane().add(jbfechar);
        jbfechar.setBounds(217, 364, 169, 37);

        jtendereco.setEnabled(false);
        jtendereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtenderecoActionPerformed(evt);
            }
        });
        getContentPane().add(jtendereco);
        jtendereco.setBounds(30, 110, 261, 36);

        jttelefone.setEnabled(false);
        jttelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jttelefoneActionPerformed(evt);
            }
        });
        getContentPane().add(jttelefone);
        jttelefone.setBounds(30, 170, 261, 40);

        jtemail.setEnabled(false);
        getContentPane().add(jtemail);
        jtemail.setBounds(30, 230, 260, 50);

        jLabel4.setText("Email:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 210, 70, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtnomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtnomeActionPerformed

    private void jbfecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbfecharActionPerformed
        // TODO add your handling code here:
        System.exit(0);
        
        
    }//GEN-LAST:event_jbfecharActionPerformed

    private void jttelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jttelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jttelefoneActionPerformed

    private void jblimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jblimparActionPerformed
        // TODO add your handling code here:
        jtnome.setText(null);
        jtendereco.setText(null);
        jttelefone.setText(null);
        jtemail.setText(null);
    }//GEN-LAST:event_jblimparActionPerformed

    private void jbnovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnovoActionPerformed
        // TODO add your handling code here
        jtnome.setEnabled(true);
        jtendereco.setEnabled(true);
        jttelefone.setEnabled(true);
        jbenviar.setEnabled(true);
        jblimpar.setEnabled(true);
        jtemail.setEnabled(true);
    }//GEN-LAST:event_jbnovoActionPerformed

    private void jtenderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtenderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtenderecoActionPerformed

    private void jbenviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbenviarActionPerformed
        // TODO add your handling code here:
        
     nome=jtnome.getText();
     endereco=jtendereco.getText();
     telefone=jttelefone.getText();
     email=jtemail.getText();
     //JOptionPane.showMessageDialog(this,nome + "\n" + endereco+ "\n "+telefone );
     System.out.println("Nome: "+nome+"\n"+"endereco: "+endereco+"\n"+"telefone:"+
             telefone+"\n"+"email: "+email);
     
     
    }//GEN-LAST:event_jbenviarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Painel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Painel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Painel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Painel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Painel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton jbenviar;
    private javax.swing.JButton jbfechar;
    private javax.swing.JButton jblimpar;
    private javax.swing.JButton jbnovo;
    private javax.swing.JTextField jtemail;
    private javax.swing.JTextField jtendereco;
    private javax.swing.JTextField jtnome;
    private javax.swing.JTextField jttelefone;
    // End of variables declaration//GEN-END:variables
}
